### ISSUE TITLE
Services with missing/unavailable dependencies

### ISSUE THREAD

**Issue by khajavi** [nebrass/pairing-shiro-javaee7#1]
When I want to deploy ShiroTutorial.war this error occurs:

17:38:56,973 ERROR [org.jboss.as.controller.management-operation](management task-7) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "ShiroTutorial.war")]) - failure description: {"WFLYCTL0180: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"ShiroTutorial.war#shiroJPU\" is missing [jboss.naming.context.java.jdbc.demo.shiro]",
    "jboss.persistenceunit.\"ShiroTutorial.war#shiroJPU\".**FIRST_PHASE** is missing [jboss.naming.context.java.jdbc.demo.shiro]"
]}
17:38:56,978 ERROR [org.jboss.as.server](management task-7) WFLYSRV0021: Deploy of deployment "ShiroTutorial.war" was rolled back with the following failure message: 
{"WFLYCTL0180: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"ShiroTutorial.war#shiroJPU\" is missing [jboss.naming.context.java.jdbc.demo.shiro]",
    "jboss.persistenceunit.\"ShiroTutorial.war#shiroJPU\".**FIRST_PHASE** is missing [jboss.naming.context.java.jdbc.demo.shiro]"

**Comment by nebrass** [comment]
Hello Khajavi,

The error that you got occured because you have not defined the required JDBC Datasource in your Wildfly. If you take a look to the persistence.xml:
`<jta-data-source>jdbc/demo/shiro</jta-data-source>`

You have to define this datasource in Wildfly, this is a good tutorial : [http://www.techpaste.com/2014/05/how-to-configure-datasource-in-jboss-wildfly/](http://www.techpaste.com/2014/05/how-to-configure-datasource-in-jboss-wildfly/)

I hope that my answer will help solve your issue :wink: 

If it's ok please confirm so that I can close the issue :smile:

**Comment by nebrass** [comment]
@khajavi it's resolved or you are facing some other errors?

**Comment by khajavi** [comment]
Hi Nebrass,
Thanks a lot for your help. This week I didn't work more on it. I will try
again soon.

On Tue, Jun 7, 2016 at 4:57 PM, Nebrass Lamouchi notifications@github.com
wrote:

> @khajavi https://github.com/khajavi it's resolved or you are facing
> some other errors?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/nebrass/pairing-shiro-javaee7/issues/1#issuecomment-224264794,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAOZxqW70vwzZULWCkDwhMGXsulJ7NPXks5qJWOUgaJpZM4Is9j4
> .

## 

﻿﻿Milād Khājavi
http://blog.khajavi.ir
Having the source means you can do it yourself.
I tried to change the world, but I couldn’t find the source code.

**Comment by nebrass** [comment]
False-positive issue. To be closed :closed_umbrella:

**Comment by 95pratik** [comment]
could you please resolve my issue
 Required services that are not installed:" => ["jboss.security.security-domain.imixsrealm"],
  "WFLYCTL0180: Services with missing/unavailable dependencies" => [
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.EntityService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.AdminPService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.EntityRestServiceV3.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ModelRestServiceV3.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.WorkflowRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ModelService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.SchedulerConfigurationService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.DocumentRestServiceV40.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ModelRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".undertow-deployment.UndertowDeploymentInfoService is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.WorkflowRestServiceV3.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.JobHandlerMigration3X.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ModelRestServiceV40.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.LoadRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.JobHandlerRenameUser.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.LuceneSearchService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.JobHandlerRebuildIndex.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.DocumentService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.AdminPRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.RootRestServiceV40.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.AdminPRestServiceV40.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.WorkflowSchedulerService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.JobHandlerUpgradeWorkitems.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.SimulationService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.LuceneUpdateService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ReportRestServiceV40.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.TextPropertyValueAdapter.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.PropertyService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.SchedulerService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ReportService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.WorkflowService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.WorkflowRestServiceV40.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.TextItemValueAdapter.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.DocumentRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.RootRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]",
    "jboss.deployment.unit.\"imixs-jsf-example-4.2.0.war\".component.ReportRestService.CREATE is missing [jboss.security.security-domain.imixsrealm]"
  ]
}
